---
framework: jest
tier: xlarge
postMerge: 
  pattern: 
    - "./tests/**/*-spec.ts"
preMerge:
  pattern:
    - "./tests/**/*-spec.ts"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 2.1
