---
framework: "jest"
postMerge:
    pattern:
    - "./tests/**/*-spec.ts"            # Glob pattern to path where tests that should run post-merge are written
preMerge:
    pattern:
    - "./tests/**/*-spec.ts"              # Glob pattern to path where tests that should run pre-merge are written
preRun:
    - npm install
    - npm run build
postRun:
    - node --version
version: 2.0
